name: Build and Publish Docker image

on:
  push:
    branches:
      - "release-*"
  workflow_dispatch:

env:
  # Image name defaults to <DOCKERHUB_USERNAME>/s3webclient
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/s3webclient

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Derive version from branch name
        id: vars
        shell: bash
        run: |
          ref="$GITHUB_REF_NAME"
          ver="${ref#release-}"
          if [[ -z "$ver" || "$ver" == "$ref" ]]; then
            echo "Branch name must be release-<version> (e.g., release-0.0.1)" >&2
            exit 1
          fi
          echo "version=$ver" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.version }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.vars.outputs.version }}
          name: Release ${{ steps.vars.outputs.version }}
          commit: ${{ github.sha }}
          body: |
            Docker image published:
            - `${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.version }}`
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
